[package]
name = "kaiten-sushi"
version = "0.1.0"
authors = ["Masaki Murano <masaki.murano@livesense.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
